apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "confluence.fullname" . }}
  labels:
    {{- include "confluence.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "confluence.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "confluence.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "confluence.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          {{- with .Values.ports }}
          ports:
          {{- toYaml . | nindent 12  }}
          {{- end }}
          
          {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 12  }}
          {{- end }}
          
          {{- if .Values.persistence.enabled -}}
          {{- with .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 12  }}
          {{- end }}
          {{- end -}}

          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12  }}
          {{- end }}

          {{- with .Values.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12  }}
          {{- end }}
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- if .Values.persistence.enabled -}}
      {{- $pvcClaimName := .Values.persistence.data.claimName -}}
      {{- range .Values.volumes }}
      volumes:
        - name: {{ . }}
        {{- if ($pvcClaimName) }}
          persistentVolumeClaim:
            claimName: {{ $pvcClaimName }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- end }}
      {{- end -}}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
