{{- if and .Values.persistence.enabled (not .Values.persistence.data.reuse_pvc) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    "helm.sh/resource-policy": keep
{{- if .Values.persistence.data.existingClaim }}
  name: "{{ .Values.persistence.data.existingClaim }}"
{{- else }}
  name: "{{ .Values.persistence.data.claimName }}"
{{- end }}
  labels:
    app: {{ template "confluence.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- if .Values.persistence.data.storageClassName }}
{{- if (eq "-" .Values.persistence.data.storageClassName) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.data.sstorageClassName }}"
{{- end }}
{{- end }}
{{- end -}}